name: bitcount
version: 0.1.1
description: >-
  Provides efficient one-bits count method extension for default int.
homepage: https://github.com/gagoman/bitcount

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
  benchmark_harness: ^1.0.0
